language: php

services:
  - mysql

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

cache:
  directories:
    - $HOME/.composer/cache

script: vendor/bin/phpunit
